version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:12.4
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatroom_app
